# Generated by Django 4.2.3 on 2023-07-24 13:02

import PawRescue.utilities.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adoption_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('contact_number', models.CharField(max_length=10, validators=[PawRescue.utilities.validators.validate_digits_only])),
                ('home_environment', models.TextField(validators=[PawRescue.utilities.validators.validate_word_count])),
                ('previous_pet_experience', models.TextField(validators=[PawRescue.utilities.validators.validate_word_count])),
                ('reason_for_adoption', models.TextField(validators=[PawRescue.utilities.validators.validate_word_count])),
                ('status', models.CharField(choices=[('Pending', 'Pending - Your Application is Under Review'), ('Accepted', 'Accepted - Expect a Call from the Pet Owner'), ('Rejected', 'Rejected - Thank You for Applying')], default='Pending', max_length=35)),
                ('is_approved', models.BooleanField(default=False)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
                ('pet_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_adoptions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApprovedAdoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_date', models.DateTimeField(auto_now_add=True)),
                ('adoption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adoption.adoption')),
            ],
        ),
    ]
