# Generated by Django 4.2.3 on 2023-07-24 13:01

import PawRescue.utilities.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='To Be Named', max_length=20)),
                ('pet_type', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Other', 'Other')], max_length=10)),
                ('other_pet_type', models.CharField(blank=True, max_length=10, null=True)),
                ('breed', models.CharField(blank=True, default='Unknown', max_length=10)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], default='Unknown', max_length=10)),
                ('description', models.TextField(validators=[PawRescue.utilities.validators.validate_word_count])),
                ('specifics_in_behavior', models.TextField(blank=True, null=True, validators=[PawRescue.utilities.validators.validate_word_count])),
                ('health_status', models.CharField(choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Serious', 'Serious'), ('Critical', 'Critical')], default='Good', max_length=10)),
                ('photo', models.ImageField(upload_to='pet_photos/')),
                ('town', models.CharField(max_length=20)),
                ('can_be_driven', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
