# Generated by Django 4.2.3 on 2023-07-21 19:14

import PawRescue.utilities.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(blank=True, default='Unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='other_pet_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='specifics_in_behavior',
            field=models.TextField(blank=True, null=True, validators=[PawRescue.utilities.validators.validate_word_count]),
        ),
        migrations.AlterField(
            model_name='pet',
            name='town',
            field=models.CharField(max_length=20),
        ),
    ]
